# Generated by Django 4.2.4 on 2023-08-20 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'New'), (2, 'Pending'), (3, 'Closed')], default=1, max_length=1)),
                ('type_of_request', models.CharField(choices=[(1, 'Normal'), (2, 'Expediate')], default=1, max_length=1)),
                ('env_swimlane', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('number_of_records', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=100)),
                ('expected_date', models.DateField()),
                ('type_of_data_setup', models.CharField(choices=[(1, 'New'), (2, 'Existing'), (3, 'Inforce'), (4, 'Gold Copy'), (5, 'Not Applicable')], default=1, max_length=1)),
                ('stakeholders', models.TextField()),
                ('state_jurisdiction', models.CharField(choices=[(1, 'New'), (2, 'Existing'), (3, 'Inforce'), (4, 'Gold Copy'), (5, 'Not Applicable')], default=1, max_length=1)),
                ('synopsis_of_request', models.TextField()),
                ('description_of_request', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('test_data', models.FileField(default=None, max_length=250, null=True, upload_to='testdata/')),
                ('requested_by', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
