# Generated by Django 4.2.4 on 2023-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assigned_to',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='application',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='env_swimlane',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_records',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='project_name',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
