# Generated by Django 4.2.4 on 2023-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_request_assigned_to_alter_request_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='request',
            name='env_swimlane',
            field=models.CharField(choices=[('qa1', 'QA1'), ('qa2', 'QA2')], default='qa1', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='state_jurisdiction',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('inforce', 'Inforce'), ('gold copy', 'Gold Copy'), ('not applicable', 'Not Applicable')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('closed', 'Closed')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='type_of_data_setup',
            field=models.CharField(choices=[('new', 'New'), ('existing', 'Existing'), ('inforce', 'Inforce'), ('gold copy', 'Gold Copy'), ('not applicable', 'Not Applicable')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='type_of_request',
            field=models.CharField(choices=[('normal', 'Normal'), ('expediate', 'Expediate')], default='normal', max_length=100),
        ),
    ]
