# Generated by Django 4.2.4 on 2023-08-24 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0004_remove_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
