# Generated by Django 4.2.4 on 2023-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0005_alter_request_assigned_to_alter_request_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
