# Generated by Django 4.2.4 on 2023-08-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0007_alter_request_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='assigned_to',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
