# Generated by Django 4.2.4 on 2023-08-24 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0008_alter_request_assigned_to_alter_request_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
